apiVersion: v1
kind: ServiceAccount
metadata:
  name: backlokto-operator-service-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: backlokto-operator-cluster-role
rules:
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["get", "create", "update", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: backlokto-operator-cluster-role-binding
subjects:
- kind: ServiceAccount
  name: backlokto-operator-service-account
  namespace: default
roleRef:
  kind: ClusterRole
  name: backlokto-operator-cluster-role
  apiGroup: rbac.authorization.k8s.io
